version: "3"
services:
  php:
    image: bitnami/php-fpm:latest
    volumes:
      - .:/app:cached
      - ./docker/php/config.ini:/opt/bitnami/php/etc/php.ini:cached
    working_dir: /app
    container_name: autoping_php

  nginx:
    image: nginx:1.15
    ports:
      - 127.0.0.1:${NGINX_PORT}:80
    volumes:
      - .:/app:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    container_name: autoping_nginx

  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - 127.0.0.1:${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
    container_name: autoping_mysql

networks:
  default:
    external:
      name: autoping
