<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\User;

abstract class  AbstractController extends \Symfony\Bundle\FrameworkBundle\Controller\AbstractController
{
    protected function getUser(): User
    {
        if (parent::getUser() === null) {
            return $this->redirectToRoute('app_login');
        }

        return parent::getUser(); // TODO: Change the autogenerated stub
    }
}